### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by iaguis** [naegelejd/go-acl#1]
Hi!

We vendored your project in [rkt](https://github.com/coreos/rkt) but we just noticed it doesn't have a license.

We will revert it anyway because we can't link to libacl but we want to make a version that uses dlopen instead of linking to libacl based on yours (https://github.com/coreos/rkt/pull/1963). Would that be ok?

In rkt we use the [Apache 2.0 license](http://www.apache.org/licenses/LICENSE-2.0) so if you could use that licence that would be great.
. 
Thanks!

**Comment by naegelejd** [comment]
Hi, thanks for reaching out!

I'm inclined to use the MIT license as I normally do. Apologies for not already including it. It's quite compatible with the Apache 2.0 license so hopefully that will work.

Much of the top-level code simply wraps libacl, so not much IP, but if you do use anything I'd like acknowledgement. Thanks, I'm looking forward to using **rkt**!

**Comment by iaguis** [comment]
Great, that should work for us. Thanks again!
